### ISSUE TITLE
CIM aliases missing

### ISSUE THREAD

**Issue by simonsigre** [enosysau/Splunk_TA_citrix_netscaler_Enosys#7]
Concern that many aliases have been missed with this TA, just need confirmation;

Examples;
`src_ip`
`dest_ip`

**Comment by linsmeyerh** [comment]
Created an additional CIM field `signature` as an alias from `Failure_reason`  

applied code to props.conf file: 
```FIELDALIAS-signature = Failure_reason AS signature```

No other missing fields reported for sourcetype `citrix:netscaler:syslog`  as of 20/03/2020.
