### ISSUE TITLE
Unable to initialize modular input

### ISSUE THREAD

**Issue by simonsigre** [enosysau/Splunk_TA_citrix_netscaler_Enosys#8]
The TA reports (when deployed in Cloud) ;
`Unable to initialize modular input "citrix_netscaler" defined inside the app "Splunk_TA_citrix-netscaler_enosys": Unable to locate suitable script for introspection.`

Splunk TAC report this to be because;

> This app contains inputs.conf which contains a modular input stanza, but the specified scripts not exist. That means this app can't run modular input correctly.

**Comment by linsmeyerh** [comment]
This issue has been resolved.
